# -*- coding: utf-8 -*-
"""Real_world_covid_Causal_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jvOSTxN2V2XVXOfpBvN_llVn12LnJdBm
"""

# ==========================================================
# CELL 1 : IMPORTS + LOAD DATA
# ==========================================================

import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import roc_auc_score

from sklearn.ensemble import RandomForestRegressor

# -----------------------
# Load Dataset
# -----------------------

df = pd.read_csv("/content/real_world_weekly_panel.csv")

print("="*70)
print("Dataset Shape")
print(df.shape)

print("\nColumns")
print(df.columns.tolist())

display(df.head())

# -------------------------------------------------------
# Future Outcome (Next Week Cases)
# -------------------------------------------------------

df = df.sort_values(
    ["country", "week"]
)

df["cases_pm_next"] = (
    df.groupby("country")["cases_pm"]
      .shift(-1)
)

# Remove last week of every country
df = df.dropna(
    subset=["cases_pm_next"]
).reset_index(drop=True)

# -----------------------
# Treatment
# -----------------------

T = df["treatment"]

Y = df["cases_pm_next"]

# -----------------------
# Covariates
# -----------------------

X = df[
    [
        "vaccination_rate",
        "population_density",
        "hospital_beds",
        "median_age",
        "age65",
        "gdp_pc"
    ]
]

print("\nTreatment Distribution")
print(T.value_counts())

print("\nOutcome Summary")
print(Y.describe())

# ==========================================================
# CELL 2 : PROPENSITY SCORE ESTIMATION
# ==========================================================


# -------------------------
# Logistic Regression
# -------------------------
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

ps_model = make_pipeline(
    StandardScaler(),
    LogisticRegression(
        max_iter=5000,
        random_state=42
    )
)


ps_model.fit(X, T)

# -------------------------
# Propensity Scores
# -------------------------

df["propensity_score"] = ps_model.predict_proba(X)[:, 1]

# -------------------------
# ROC-AUC
# -------------------------

auc = roc_auc_score(T, df["propensity_score"])

print("="*70)
print("Propensity Score Model")
print("="*70)

print(f"ROC-AUC : {auc:.3f}")

print("\nPropensity Score Summary")

display(
    df["propensity_score"].describe()
)

print("\nFirst Five Scores")

display(
    df[
        [
            "country",
            "week",
            "treatment",
            "propensity_score"
        ]
    ].head()
)

# ==========================================================
# CELL 3 : PROPENSITY SCORE MATCHING (PSM)
# ==========================================================

from sklearn.neighbors import NearestNeighbors

# -------------------------
# Split treated and control
# -------------------------

treated = df[df["treatment"] == 1].copy()
control = df[df["treatment"] == 0].copy()

# -------------------------
# Nearest Neighbour Matching
# -------------------------

nn = NearestNeighbors(n_neighbors=1)

nn.fit(control[["propensity_score"]])

distances, indices = nn.kneighbors(
    treated[["propensity_score"]]
)

matched_control = control.iloc[indices.flatten()].copy()

# -------------------------
# ATT
# -------------------------

psm_att = (
    treated["cases_pm"].values
    - matched_control["cases_pm"].values
).mean()

print("=" * 70)
print("Propensity Score Matching")
print("=" * 70)

print(f"Matched Treated Units : {len(treated)}")
print(f"Matched Control Units : {len(matched_control)}")
print(f"Estimated ATT : {psm_att:.4f}")

# -------------------------
# Standardized Mean Difference
# -------------------------

covariates = [
    "vaccination_rate",
    "population_density",
    "hospital_beds",
    "median_age",
    "age65",
    "gdp_pc"
]

balance = []

for col in covariates:

    mt = treated[col].mean()
    mc = matched_control[col].mean()

    vt = treated[col].var()
    vc = matched_control[col].var()

    smd = (mt - mc) / np.sqrt((vt + vc) / 2)

    balance.append([col, smd])

balance = pd.DataFrame(
    balance,
    columns=["Covariate", "SMD"]
)

print("\nStandardized Mean Difference")
display(balance)

print("\nAverage |SMD| :", balance["SMD"].abs().mean())

# ==========================================================
# CELL 4 : IPW + AIPW
# ==========================================================

from sklearn.ensemble import RandomForestRegressor

# -------------------------------------------------------
# Stabilized IPW
# -------------------------------------------------------

p_treat = T.mean()

df["ipw"] = np.where(
    T == 1,
    p_treat / df["propensity_score"],
    (1 - p_treat) / (1 - df["propensity_score"])
)

# -------------------------------------------------------
# IPW ATE
# -------------------------------------------------------

ipw_ate = (
    np.sum(df["ipw"] * T * Y) / np.sum(df["ipw"] * T)
) - (
    np.sum(df["ipw"] * (1 - T) * Y) / np.sum(df["ipw"] * (1 - T))
)

# -------------------------------------------------------
# Outcome Models
# -------------------------------------------------------

rf_treated = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf_control = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf_treated.fit(
    X[T == 1],
    Y[T == 1]
)

rf_control.fit(
    X[T == 0],
    Y[T == 0]
)

mu1 = rf_treated.predict(X)
mu0 = rf_control.predict(X)

# -------------------------------------------------------
# AIPW
# -------------------------------------------------------

aipw = (
    mu1
    - mu0
    + T * (Y - mu1) / df["propensity_score"]
    - (1 - T) * (Y - mu0) / (1 - df["propensity_score"])
)

aipw_ate = aipw.mean()

# -------------------------------------------------------
# Results
# -------------------------------------------------------

print("=" * 70)
print("Inverse Probability Weighting")
print("=" * 70)

print(f"Estimated IPW ATE  : {ipw_ate:.4f}")

print("\nWeight Summary")

display(df["ipw"].describe())

print("\n")

print("=" * 70)
print("Augmented IPW")
print("=" * 70)

print(f"Estimated AIPW ATE : {aipw_ate:.4f}")

!pip install dowhy econml -q

# ==========================================================
# CELL 5 : DoWhy + EconML
# ==========================================================

from dowhy import CausalModel
from econml.dml import CausalForestDML
from sklearn.ensemble import RandomForestRegressor

# -------------------------------------------------------
# DoWhy
# -------------------------------------------------------

causal_df = df.copy()

model = CausalModel(
    data=causal_df,
    treatment="treatment",
    outcome="cases_pm_next",
    common_causes=[
        "vaccination_rate",
        "population_density",
        "hospital_beds",
        "median_age",
        "age65",
        "gdp_pc"
    ]
)

identified_estimand = model.identify_effect()

estimate = model.estimate_effect(
    identified_estimand,
    method_name="backdoor.propensity_score_weighting"
)

print("=" * 70)
print("DoWhy")
print("=" * 70)

print("Estimated ATE :", estimate.value)

# -------------------------------------------------------
# EconML
# -------------------------------------------------------

cf = CausalForestDML(
    model_y=RandomForestRegressor(
        n_estimators=200,
        random_state=42
    ),
    model_t=RandomForestRegressor(
        n_estimators=200,
        random_state=42
    ),
    random_state=42
)

cf.fit(
    Y,
    T,
    X=X
)

ite = cf.effect(X)

print("\n")

print("=" * 70)
print("EconML")
print("=" * 70)

print("Average Treatment Effect :", ite.mean())

causal_df["ITE"] = ite

display(
    causal_df[
        [
            "country",
            "week",
            "ITE"
        ]
    ].head()
)

# ==========================================================
# CELL 6 : FINAL COMPARISON
# ==========================================================

comparison = pd.DataFrame({

    "Method":[
        "PS Matching",
        "IPW",
        "AIPW",
        "DoWhy",
        "EconML"
    ],

    "Synthetic Result":[
        -0.001948,
        -0.001715,
        -0.000581,
        -0.000442,
        "ITE Distribution"
    ],

    "Real Result":[
        round(psm_att,3),
        round(ipw_ate,3),
        round(aipw_ate,3),
        round(estimate.value,3),
        round(ite.mean(),3)
    ]

})

print("="*70)
print("FINAL COMPARISON")
print("="*70)

display(comparison)

comparison.to_csv(
    "causal_comparison_results.csv",
    index=False
)

import matplotlib.pyplot as plt

methods = [
    "PSM",
    "IPW",
    "AIPW",
    "DoWhy",
    "EconML"
]

values = [
    psm_att,
    ipw_ate,
    aipw_ate,
    estimate.value,
    ite.mean()
]

plt.figure(figsize=(8,5))

plt.bar(methods, values)

plt.ylabel("Estimated Treatment Effect")

plt.title("Comparison of Causal Estimators on Real Dataset")

plt.show()