# -*- coding: utf-8 -*-
"""real_world_data_preparation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hTJqvU5xe8Sp8k6WThP6D6jGhOHqDwyH

# Real-World Data Preparation

## Objective

This notebook prepares the real-world COVID-19 observational dataset for causal inference analysis.

### Data Sources
- Our World in Data (OWID)
- Oxford COVID-19 Government Response Tracker (OxCGRT)

### Final Outcome
A clean country-week panel dataset for validating causal inference methods developed on the synthetic benchmark dataset.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ==========================================================
# Load datasets
# ==========================================================

owid = pd.read_csv("/content/owid-covid-data.csv")
ox = pd.read_csv("/content/OxCGRT_compact_national_v1.csv")

# ==========================================================
# Select required variables
# ==========================================================

owid = owid[
    [
        "location",
        "date",
        "new_cases_per_million",
        "people_vaccinated_per_hundred",
        "population_density",
        "hospital_beds_per_thousand",
        "median_age",
        "aged_65_older",
        "gdp_per_capita"
    ]
].copy()

ox = ox[
    [
        "CountryName",
        "Date",
        "StringencyIndex_Average"
    ]
].copy()

# ==========================================================
# Rename columns
# ==========================================================

owid.rename(columns={
    "location": "country",
    "new_cases_per_million": "cases_pm",
    "people_vaccinated_per_hundred": "vaccination_rate",
    "hospital_beds_per_thousand": "hospital_beds",
    "aged_65_older": "age65",
    "gdp_per_capita": "gdp_pc"
}, inplace=True)

ox.rename(columns={
    "CountryName": "country",
    "Date": "date",
    "StringencyIndex_Average": "stringency"
}, inplace=True)

# ==========================================================
# Convert dates
# ==========================================================

owid["date"] = pd.to_datetime(owid["date"])

ox["date"] = pd.to_datetime(
    ox["date"].astype(str),
    format="%Y%m%d"
)

# ==========================================================
# Filter to 2021
# ==========================================================

start_date = "2021-01-01"
end_date = "2021-12-31"

owid = owid[
    (owid["date"] >= start_date) &
    (owid["date"] <= end_date)
].copy()

ox = ox[
    (ox["date"] >= start_date) &
    (ox["date"] <= end_date)
].copy()

# ==========================================================
# Summary
# ==========================================================

print("="*70)
print("OWID")
print("="*70)
print("Shape :", owid.shape)
print("Countries :", owid["country"].nunique())

print()

print("="*70)
print("OxCGRT")
print("="*70)
print("Shape :", ox.shape)
print("Countries :", ox["country"].nunique())

# ==========================================================
# Merge datasets
# ==========================================================

master = pd.merge(
    owid,
    ox,
    on=["country", "date"],
    how="inner"
)

# ==========================================================
# Basic quality checks
# ==========================================================

print("="*70)
print("MASTER DATASET")
print("="*70)

print(f"Shape              : {master.shape}")
print(f"Countries          : {master['country'].nunique()}")
print(f"Duplicate rows     : {master.duplicated(subset=['country','date']).sum()}")

print("\n")

print("="*70)
print("Missing Values")
print("="*70)

display(
    master.isna()
    .sum()
    .sort_values(ascending=False)
    .to_frame("Missing Values")
)

print("\n")

print("="*70)
print("India Check")
print("="*70)

display(
    master[
        master["country"]=="India"
    ].head()
)

print(
    "India rows :",
    len(master[master["country"]=="India"])
)

# ==========================================================
# Handle Missing Values
# ==========================================================

# Static country-level variables
static_cols = [
    "population_density",
    "hospital_beds",
    "median_age",
    "age65",
    "gdp_pc"
]

master[static_cols] = (
    master
    .groupby("country")[static_cols]
    .transform(lambda x: x.ffill().bfill())
)

# Vaccination
master["vaccination_rate"] = (
    master["vaccination_rate"]
    .fillna(0)
)

# Remove rows with missing outcome
master = master.dropna(
    subset=["cases_pm"]
)

# ==========================================================
# Final Missing Value Check
# ==========================================================

print("="*70)
print("Remaining Missing Values")
print("="*70)

display(
    master.isna()
    .sum()
    .sort_values(ascending=False)
)

# ==========================================================
# Country Quality Audit
# ==========================================================

important_cols = [
    "population_density",
    "hospital_beds",
    "median_age",
    "age65",
    "gdp_pc"
]

country_quality = (
    master
    .groupby("country")[important_cols]
    .apply(lambda x: x.isna().mean().mean())
    .to_frame("missing_fraction")
    .sort_values("missing_fraction")
)

print(country_quality.head(20))

print("\n")

print(country_quality.tail(20))

plt.figure(figsize=(8,5))

country_quality["missing_fraction"].hist(
    bins=20
)

plt.xlabel("Average Missing Fraction")
plt.ylabel("Countries")
plt.title("Country Data Quality")

plt.show()

# ==========================================================
# Keep only high-quality countries
# ==========================================================

QUALITY_THRESHOLD = 0.10

good_countries = country_quality[
    country_quality["missing_fraction"] <= QUALITY_THRESHOLD
].index

master = master[
    master["country"].isin(good_countries)
].copy()

print("="*70)
print("Dataset After Country Filtering")
print("="*70)

print(f"Rows      : {master.shape[0]}")
print(f"Countries : {master['country'].nunique()}")

print("\nRemaining Missing Values\n")

display(
    master.isna().sum().sort_values(ascending=False)
)

# ==========================================================
# Construct Weekly Country Panel
# ==========================================================

master["week"] = master["date"].dt.to_period("W").apply(lambda r: r.start_time)

weekly = (
    master
    .groupby(["country", "week"], as_index=False)
    .agg(
        cases_pm=("cases_pm", "mean"),
        vaccination_rate=("vaccination_rate", "mean"),
        stringency=("stringency", "mean"),
        population_density=("population_density", "first"),
        hospital_beds=("hospital_beds", "first"),
        median_age=("median_age", "first"),
        age65=("age65", "first"),
        gdp_pc=("gdp_pc", "first")
    )
)

print("=" * 70)
print("Weekly Dataset")
print("=" * 70)

print(f"Shape      : {weekly.shape}")
print(f"Countries  : {weekly['country'].nunique()}")
print(f"Weeks      : {weekly['week'].nunique()}")

display(weekly.head())

# ==========================================================
# Explore Stringency Index
# ==========================================================

print(weekly["stringency"].describe())

plt.figure(figsize=(8,5))
plt.hist(weekly["stringency"], bins=30, edgecolor="black")

plt.xlabel("Weekly Average Stringency Index")
plt.ylabel("Number of Observations")
plt.title("Distribution of Weekly Stringency")

plt.show()

# ==========================================================
# Define Binary Treatment
# ==========================================================

threshold = weekly["stringency"].median()

weekly["treatment"] = (
    weekly["stringency"] >= threshold
).astype(int)

print("="*70)
print("Treatment Threshold")
print("="*70)

print(f"Median Stringency Threshold : {threshold:.2f}")

print("\nTreatment Distribution\n")

print(weekly["treatment"].value_counts())

print("\nPercentage Distribution\n")

print(
    (weekly["treatment"]
     .value_counts(normalize=True)*100)
    .round(2)
)

display(weekly.head())

weekly = weekly[
    weekly["week"] >= pd.Timestamp("2021-01-04")
].copy()

print(weekly.shape)

weekly.to_csv("real_world_weekly_panel.csv", index=False)

print("Dataset saved successfully!")



















